### **1. Cutlets**

Assume Null Hypothesis as Ho: µ1 = µ2 (There is no difference in diameter of cutlets between two units)

Thus Alternate Hypotheis as Ha: µ1≠ µ2 (There is significant differenece in diameter of cutlets between two units) 2 Sample 2 Tail Test

In [ ]:
#Importing Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from scipy import stats

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Cutlets.csv to Cutlets.csv

In [ ]:
df = pd.read_csv("Cutlets.csv")

In [ ]:
#Displaying Contents
df

    Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [ ]:
#Displaying First 5 Items
df.head()

   Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
#Displaying Last 5 Items
df.tail()

    Unit A  Unit B
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [ ]:
#Describing the Data
df.describe()

          Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes

In [ ]:
df.shape

(35, 2)

In [ ]:
#Checks whether any Null items is present or not
df.isnull().any()

Unit A    False
Unit B    False
dtype: bool

In [ ]:
#Number of Null Items
df.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

In [ ]:
#Displaying the data items on the first column
col_1 = pd.Series(df.iloc[:,0])
col_1

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [ ]:
#Displaying the data items on the second column
col_2 = pd.Series(df.iloc[:,1])
col_2

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [ ]:
#Checks P value
p_value = stats.ttest_ind(col_1,col_2)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [ ]:
p_value[1]

0.4722394724599501

## Here, alpha=0.5,Hence Pvalue is less than alpha
## **So we reject Null Hypothesis**

# 2. **LabTat**

Assume Null Hypotheis as Ho= No variance(All samples TAT population means are same)

Alternate Hypothesis as Ha= Has Variance(Atleast one sample TAT population means is different)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving LabTAT.csv to LabTAT.csv

In [ ]:
lab = pd.read_csv("LabTAT.csv")
lab

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [ ]:
#Display First 5 items
lab.head()

   Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [ ]:
#Display Last 5 items
lab.tail()

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

In [ ]:
lab.describe()

       Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [ ]:
lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB

In [ ]:
#Checks the number of Null Items 
lab.isnull().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [ ]:
#To display the first column elements
L1 = pd.Series(lab.iloc[:,0])
L1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [ ]:
#To display the second column elements
L2 = pd.Series(lab.iloc[:,1])
L2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [ ]:
#To display the third column elements
L3 = pd.Series(lab.iloc[:,2])
L3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [ ]:
#To display the Fourth column elements
L4 = pd.Series(lab.iloc[:,3])
L4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [ ]:
p_value = stats.f_oneway(L1,L2,L3,L4)
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
p_value[1]

2.1156708949992414e-57

### Comparing P-Value with Alpha=0.5,Hence P-Value Is less than alpha
## **Reject Null Hypotheis**

## **3.Buyer Ratio**

In [21]:
from scipy.stats import chi2
from scipy.stats import chi2_contingency

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving BuyerRatio.csv to BuyerRatio.csv

In [ ]:
data = pd.read_csv("BuyerRatio.csv")
data

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
data.isnull().sum()

Observed Values    0
East               0
West               0
North              0
South              0
dtype: int64

In [ ]:
data.head()

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64
 2   West             2 non-null      int64
 3   North            2 non-null      int64
 4   South            2 non-null      int64
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes

In [ ]:
data.describe()

             East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [ ]:
data.shape

(2, 5)

In [22]:
observed = np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)

chi_val, p_val, dof, expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

As P value is greater than alpha Hence,we will fail to reject Null Hypothesis(Ho)

Pvalue > alpha = (0.66 > 0.5)

## **Accept Null Hypothesis**

## Customer Order Form

In [23]:
from scipy.stats import chi2_contingency

In [24]:
from google.colab import files
uploaded = files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm.csv

In [25]:
cof = pd.read_csv("Costomer+OrderForm.csv")
cof

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [26]:
cof.head()

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [27]:
cof.tail()

    Phillippines   Indonesia       Malta       India
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

In [28]:
cof.describe

<bound method NDFrame.describe of     Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]>

In [29]:
cof.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [30]:
cof.dtypes

Phillippines    object
Indonesia       object
Malta           object
India           object
dtype: object

In [ ]:
cof.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [31]:
cof.mode()

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free  Error Free  Error Free

In [ ]:
cof.isnull().sum()

Phillippines    0
Indonesia       0
Malta           0
India           0
dtype: int64

In [ ]:
cof.shape

(300, 4)

In [35]:
print(cof['Phillippines'].value_counts(), cof['Indonesia'].value_counts(),cof['Malta'].value_counts(),cof['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64

In [36]:
observed = ([[271,267,269,280],[29,33,31,20]])
observed

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [37]:
stat, p, dof, expected = chi2_contingency([[271,267,269,280],[29,33,31,20]])
stat

3.858960685820355

In [38]:
alpha = 0.05
prob = 1-alpha
critical = chi2.ppf(prob,dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
	print('Dependent (reject H0),variables are related')
else:
	print('Independent (fail to reject H0), variables are not related')

probability=0.950, critical=7.815, stat=3.859
Independent (fail to reject H0), variables are not related

In [39]:
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

significance=0.050, p=0.277
Independent (fail to reject H0)